source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from to_do_list.views import (
    IndexView,
    TaskDetailView,
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskUsersUpdateView,
    SelectProjectUpdateView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('detail/<int:pk>', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('list/', TaskListView.as_view(), name='task_list'),
    path('update/<int:pk>', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('detail/<int:pk>/manage', TaskUsersUpdateView.as_view(), name='manage_users_task'),
    path('detail/<int:pk>/project', SelectProjectUpdateView.as_view(), name='select_project'),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Project(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Name')
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Description')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')
    member = models.ManyToManyField(get_user_model(), related_name='projects', blank=True)

    def __str__(self):
        return self.name

    def members(self):
        return ", ".join([str(i) for i in self.member.all()])

templates/partials/CRU.html
{% csrf_token %}

<div>
    {% for error in non_field_errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
        <div>
            <label class="form-label mt-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary mt-3">{{ button_text }}</button>
</div>

templates/partials/footer.html
<footer class="bd-footer py-4 py-md-2 mt-5 bg-body-tertiary">
    <div class="container py-4 py-md-1 px-4 px-md-3 text-body-secondary">
      <div class="row">
        <div class="col-lg-3 mb-3">
          <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
            <img src="https://w7.pngwing.com/pngs/601/588/png-transparent-logo-s-angle-triangle-poster.png" width="40" height="32" class="d-block me-2">
            <span class="fs-5">Sup To Do List</span>
          </a>
          <ul class="list-unstyled small">
            <li class="mb-2">Разработано в рамках Практического задания <a href="https://programs.outpeer.kz/">Outpeer.kz</a> с помощью <a href="https://getbootstrap.com">Bootstrap</a>.</li>
            <li class="mb-2">Currently v.1.0.</li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 offset-lg-1 mb-3">
          <h5>Links</h5>
          <ul class="list-unstyled">
            <li class="mb-2"><a href="{% url 'home_page' %}">Home</a></li>
            <li class="mb-2"><a href="{% url 'task_list' %}">Tasks list</a></li>
            <li class="mb-2"><a href="https://gitlab.com/slimon/supstore" target="_blank">Gitlab Project</a></li>
            <li class="mb-2"><a href="https://t.me/supalish" target="_blank">Telegram</a></li>
            <li class="mb-2"><a href="mailto:supalish@gmail.com" target="_blank">Email</a></li>
          </ul>
        </div>
        </div>
      </div>
    </div>
</footer>

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href={% url 'home_page' %}>SupToDoList</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home Page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_list' %}">TasksList</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_create' %}">Create Task</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'project_list' %}">Projects</a>
          </li>
          {% if perms.projects.add_project %}
          <li>
            <a class="nav-link" href="{% url 'project_create' %}">Project add</a>
          </li>
          {% endif %}
        </ul>
          <div class="d-flex ms-auto">
            {% if not request.user.is_authenticated %}
              <button type="button" class="btn btn-sm btn-primary me-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Login
              </button>
              <a class="btn btn-primary btn-sm" aria-current="page" href="{% url 'register' %}?next={{ request.get_full_path }}">Register</a>

            {% else %}
              <div class="d-flex align-items-center me-3 ms-auto">Hello, <a class="ms-1" href="{% url 'user_detail' user.pk %}">{{ user.username }}</a></div>
              <a class="btn btn-sm btn-success" aria-current="page" href="{% url 'logout' %}">Logout</a>
            {% endif %}

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                          <h1 class="modal-title fs-5" id="exampleModalLabel">Login</h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                          <form action="{% url 'login' %}" method="POST">
                            {% csrf_token %}

                            <div class="mb-3">
                              <label for="username" class="form-label">Username</label>
                              <input type="text" name="username" id="username" class="form-control">
                            </div>
                            
                            <div class="mb-3">
                              <label for="password" class="form-label">Password</label>
                              <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </form>
                      </div>
                    </div>
                  </div>
                </div>

          </div>

      </div>
    </div>
  </nav>

templates/partials/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="?page=1">1</a>
        </li>
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
            </li>    
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
        {% endif %}
        
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{ page }}" class="page-link">{{ page }}</a>
            </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
            </li>    
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
        {% endif %}
        
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">Last</a>
        </li>
    </ul>
  </nav>

templates/partials/user_form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="multipart/form-data" class="w-50">
        {% csrf_token %}
{% endif %}
        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            <div class="input-group mb-3">
                <span class="input-group-text">{{ field.label }}</span>
                {{ field }}
                
                {% for error in field.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}

{% if not fields_only %}
        <button type="submit" class="btn btn-primary">{{ button_text|default:"Submit" }}</button>
    </form>
{% endif %}