source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from to_do_list.views import (
    IndexView,
    TaskDetailView,
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskUsersUpdateView,
    SelectProjectUpdateView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('detail/<int:pk>', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('list/', TaskListView.as_view(), name='task_list'),
    path('update/<int:pk>', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('detail/<int:pk>/manage', TaskUsersUpdateView.as_view(), name='manage_users_task'),
    path('detail/<int:pk>/project', SelectProjectUpdateView.as_view(), name='select_project'),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Project(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Name')
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Description')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')
    member = models.ManyToManyField(get_user_model(), related_name='projects', blank=True)

    def __str__(self):
        return self.name

    def members(self):
        return ", ".join([str(i) for i in self.member.all()])

to_do_list/models.py
from django.db import models
from django.contrib.auth import get_user_model
from projects.models import Project

class Task(models.Model):
    class Status(models.TextChoices):
        Inprogress = 'In progress'
        Done = 'Done'
        Pending = 'Pending'

    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Title')
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Description')
    status = models.CharField(max_length = 50, choices=Status.choices, default=Status.Inprogress, verbose_name='Status')
    task_assigned_to = models.ManyToManyField(get_user_model(), related_name='tasks', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time')
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, null=True, blank=True, related_name='tasks', verbose_name='Project')

    def __str__(self):
        return f'{self.title}'
    
    def assigned_to(self):
        return ", ".join([str(i) for i in self.task_assigned_to.all()])
    
    def project_assigned(self):
        return f'{self.project}'

    

templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Task</h1>
    <form action="{% url 'task_create' %}" method="POST">
        {% include 'partials/CRU.html' with button_text="Edit" %}           
    </form>
{% endblock %}

templates/tasks/delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h1>Are you sure to delete Task<i>"{{ task.title }}"</i>?</h1>
            <form action="{% url 'task_delete' task.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Confirm</button>
                <a href="{% url 'task_detail' task.pk %}" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/tasks/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
    <div class="card-header">
        <h3 class="mt-1 mb-1">Task detail</h3>
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ task.pk }} - {{ task.title }}</h5>
        <p class="card-text">{{ task.description }}</p>
        <p class="card-text small fw-lighter">Current Status: {{ task.status }}</p>
        <p class="card-text">Task assigned to: {{ task.assigned_to }}</p>    
        {% if perms.to_do_list.delete_task and request.user in project.member.all or request.user.is_superuser %}
            <a href="{% url 'manage_users_task' task.pk %}" class="btn btn-outline-secondary btn-sm mb-3">Manage Users</a>
        {% endif %}

        {% if not project %}
            {% if perms.projects.add_project %}
            <a href="{% url 'select_project' task.pk %}" class="btn btn-outline-secondary">Select Project</a>
            {% endif %}
        {% else %}
            <p class="card-text">Project link: <a href="{% url 'project_detail' project.pk %}">{{ task.project.name }}</a></p>    
        {% endif %}


        {% if perms.to_do_list.change_task and request.user in project.member.all or request.user.is_superuser %}
            <a href="{% url 'task_update' task.pk %}" class="btn btn-outline-secondary">Update</a>
        {% endif %}
        {% if perms.to_do_list.delete_task and request.user in project.member.all or request.user.is_superuser %}
            <a href="{% url 'task_delete' task.pk %}" class="btn btn-outline-danger">Delete</a>
        {% endif %}
    </div>
    </div>

{% endblock %}

templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-sm-8">
                <form method="GET">
                    <div class="input-group">
                        <input type="search" name="search" class="form-control" aria-label="Search">
                        <button class="btn btn-success" id="button-addon2">Search</button>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                <div class="btn-group m-1 gap-2 d-flex flex-row-reverse">
                    <form method="GET" class="d-flex align-items-center">
                        <button name="sort_by" type="submit" class="btn btn-outline-dark btn-sm" value="status" id="sort_by">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-down" viewBox="0 0 16 16">
                            <path d="M3.5 2.5a.5.5 0 0 0-1 0v8.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L3.5 11.293zm3.5 1a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5M7.5 6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"/>
                            </svg> Status</button>
                    </form>
                    <form method="GET" class="d-flex align-items-center">
                        <button name="sort_by" type="submit" class="btn btn-outline-dark btn-sm" value="title" id="sort_by">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-down" viewBox="0 0 16 16">
                            <path d="M3.5 2.5a.5.5 0 0 0-1 0v8.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L3.5 11.293zm3.5 1a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5M7.5 6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"/>
                            </svg> title</button>
                    </form>
                    <form method="GET" class="d-flex align-items-center">
                        <button name="sort_by" type="submit" class="btn btn-outline-dark btn-sm" value="created_at" id="sort_by">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-down" viewBox="0 0 16 16">
                            <path d="M3.5 2.5a.5.5 0 0 0-1 0v8.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L3.5 11.293zm3.5 1a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5M7.5 6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"/>
                            </svg> Date</button>
                    </form>
                    <form method="GET" class="d-flex align-items-center">
                        <button name="sort_by" type="submit" class="btn btn-outline-dark btn-sm" value="id" id="sort_by">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-down" viewBox="0 0 16 16">
                            <path d="M3.5 2.5a.5.5 0 0 0-1 0v8.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L3.5 11.293zm3.5 1a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5M7.5 6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"/>
                            </svg> ID</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="list-group mb-3">
            {% for task in tasks %}
            <div>
                <a href="{% url 'task_detail' task.pk %}" class="list-group-item list-group-item-action mb-1">
                    <span>{{ task.id }} - {{ task.title }}
                        {% if task.status == 'Done' %}
                        <span class="badge text-bg-success">{{ task.status }}</span>
                        {% elif task.status == 'Pending' %}
                        <span class="badge text-bg-secondary">{{ task.status }}</span>            
                        {% else %}
                        <span class="badge text-bg-primary">{{ task.status }}</span>
                        {% endif %}
                        <span class="small fw-lighter">Task assigned to: {{ task.assigned_to }}</span>
                    </span>
                </a>
            </div>
            {% endfor %}
        </div>
    <div class="d-flex justify-content-center">  
        {% include 'partials/pagination.html' %}
    </div>  
    </div>
{% endblock %}

templates/tasks/manage_users_task.html
{% extends 'base.html' %}

{% block content %}
    <h1>Manage Project members</h1>
    <form action="{% url 'manage_users_task' task.pk %}" method="POST">
        {% include 'partials/CRU.html' with button_text="Edit Users" %}        
    </form>
{% endblock %}

templates/tasks/select_project.html
{% extends 'base.html' %}

{% block content %}
    <h1>Select project</h1>
    <form action="{% url 'select_project' task.pk %}" method="POST">
        {% include 'partials/CRU.html' with button_text="Select Project" %}        
    </form>
{% endblock %}

templates/tasks/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Task</h1>
    <form action="{% url 'task_update' task.pk %}" method="POST">
        {% include 'partials/CRU.html' with button_text="Edit" %}           
    </form>
{% endblock %}